// Karnataka administrative data for searchable dropdowns.
// Not exhaustive — users can also type any custom value.

export const KARNATAKA_DISTRICTS: string[] = [
  "Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban",
  "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga",
  "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan",
  "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal",
  "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga",
  "Tumakuru", "Udupi", "Uttara Kannada", "Vijayanagara", "Vijayapura",
  "Yadgir",
];

export const TALUKS_BY_DISTRICT: Record<string, string[]> = {
  "Bengaluru Urban": ["Bengaluru North", "Bengaluru South", "Bengaluru East", "Anekal", "Yelahanka"],
  "Bengaluru Rural": ["Devanahalli", "Doddaballapur", "Hoskote", "Nelamangala"],
  "Mysuru": ["Mysuru", "Hunsur", "K.R. Nagar", "Nanjangud", "T. Narasipura", "Periyapatna", "H.D. Kote"],
  "Mandya": ["Mandya", "Maddur", "Malavalli", "Nagamangala", "Pandavapura", "K.R. Pete", "Srirangapatna"],
  "Hassan": ["Hassan", "Arsikere", "Arkalgud", "Belur", "Channarayapatna", "Holenarasipura", "Sakleshpur", "Alur"],
  "Kodagu": ["Madikeri", "Somwarpet", "Virajpet", "Kushalnagar"],
  "Dakshina Kannada": ["Mangaluru", "Bantwal", "Puttur", "Sullia", "Belthangady", "Moodabidri", "Kadaba"],
  "Udupi": ["Udupi", "Kundapur", "Karkala", "Byndoor", "Kaup", "Hebri"],
  "Uttara Kannada": ["Karwar", "Sirsi", "Kumta", "Honnavar", "Bhatkal", "Ankola", "Yellapur", "Haliyal", "Dandeli", "Mundgod", "Siddapur", "Joida"],
  "Shivamogga": ["Shivamogga", "Bhadravathi", "Sagara", "Shikaripura", "Sorab", "Thirthahalli", "Hosanagara"],
  "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Tarikere", "Koppa", "Sringeri", "Mudigere", "N.R. Pura"],
  "Chitradurga": ["Chitradurga", "Hiriyur", "Hosdurga", "Holalkere", "Molakalmuru", "Challakere"],
  "Davanagere": ["Davanagere", "Harihar", "Honnali", "Jagalur", "Channagiri", "Nyamati"],
  "Tumakuru": ["Tumakuru", "Tiptur", "Kunigal", "Sira", "Chiknayakanhalli", "Turuvekere", "Pavagada", "Madhugiri", "Koratagere", "Gubbi"],
  "Ramanagara": ["Ramanagara", "Channapatna", "Kanakapura", "Magadi", "Harohalli"],
  "Chikkaballapur": ["Chikkaballapur", "Bagepalli", "Chintamani", "Gauribidanur", "Gudibande", "Sidlaghatta"],
  "Kolar": ["Kolar", "Bangarapet", "KGF", "Malur", "Mulbagal", "Srinivaspur"],
  "Belagavi": ["Belagavi", "Athani", "Bailhongal", "Chikodi", "Gokak", "Hukkeri", "Khanapur", "Raibag", "Ramdurg", "Saundatti", "Nippani"],
  "Bagalkot": ["Bagalkot", "Badami", "Bilagi", "Hungund", "Jamkhandi", "Mudhol", "Guledgudda", "Rabkavi Banhatti", "Ilkal"],
  "Vijayapura": ["Vijayapura", "Basavana Bagevadi", "Indi", "Muddebihal", "Sindgi", "Talikot", "Devar Hippargi", "Nidagundi", "Chadchan", "Kolhar"],
  "Bidar": ["Bidar", "Bhalki", "Basavakalyan", "Humnabad", "Aurad", "Chitgoppa", "Kamalnagar", "Hulsoor"],
  "Kalaburagi": ["Kalaburagi", "Afzalpur", "Aland", "Chincholi", "Chittapur", "Jevargi", "Sedam", "Yadrami", "Kamalapur", "Kalgi", "Shahabad"],
  "Yadgir": ["Yadgir", "Shahapur", "Shorapur", "Hunsagi", "Vadagera", "Gurmatkal"],
  "Raichur": ["Raichur", "Manvi", "Devadurga", "Lingasugur", "Sindhanur", "Sirwar", "Maski"],
  "Koppal": ["Koppal", "Gangavathi", "Kushtagi", "Yelburga", "Kanakagiri", "Karatgi", "Kukanoor"],
  "Ballari": ["Ballari", "Siruguppa", "Sanduru", "Kampli", "Kurugodu"],
  "Vijayanagara": ["Hosapete", "Hagaribommanahalli", "Harapanahalli", "Kottur", "Kudligi", "Huvina Hadagali"],
  "Gadag": ["Gadag-Betageri", "Ron", "Naragund", "Shirahatti", "Mundargi", "Lakshmeshwara", "Gajendragad"],
  "Dharwad": ["Dharwad", "Hubballi", "Kalghatgi", "Kundgol", "Navalgund", "Alnavar", "Annigeri"],
  "Haveri": ["Haveri", "Ranebennur", "Byadgi", "Hangal", "Hirekerur", "Savanur", "Shiggaon", "Rattihalli"],
  "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur", "Hanur"],
};

export const CITIES_BY_DISTRICT: Record<string, string[]> = {
  "Bengaluru Urban": ["Bengaluru", "Whitefield", "Electronic City", "Yelahanka", "Anekal", "Hebbal", "HSR Layout", "Koramangala", "Indiranagar", "Jayanagar", "Malleshwaram"],
  "Bengaluru Rural": ["Devanahalli", "Doddaballapur", "Hoskote", "Nelamangala", "Vijayapura"],
  "Mysuru": ["Mysuru", "Hunsur", "Nanjangud", "K.R. Nagar", "T. Narasipura", "Periyapatna", "Bettadapura", "Hootagalli"],
  "Mandya": ["Mandya", "Maddur", "Malavalli", "K.R. Pete", "Srirangapatna", "Pandavapura", "Nagamangala"],
  "Hassan": ["Hassan", "Arsikere", "Sakleshpur", "Channarayapatna", "Holenarasipura", "Belur", "Alur", "Arkalgud"],
  "Dakshina Kannada": ["Mangaluru", "Puttur", "Bantwal", "Sullia", "Moodabidri", "Belthangady", "Ullal"],
  "Udupi": ["Udupi", "Manipal", "Kundapur", "Karkala", "Kaup", "Byndoor", "Malpe"],
  "Uttara Kannada": ["Karwar", "Sirsi", "Kumta", "Honnavar", "Bhatkal", "Dandeli", "Ankola"],
  "Shivamogga": ["Shivamogga", "Bhadravathi", "Sagara", "Shikaripura", "Thirthahalli", "Hosanagara", "Sorab", "Jog Falls"],
  "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Tarikere", "Koppa", "Sringeri", "Mudigere"],
  "Kodagu": ["Madikeri", "Kushalnagar", "Virajpet", "Somwarpet", "Gonikoppal"],
  "Chitradurga": ["Chitradurga", "Hiriyur", "Hosdurga", "Challakere", "Holalkere", "Molakalmuru"],
  "Davanagere": ["Davanagere", "Harihar", "Honnali", "Jagalur", "Channagiri"],
  "Tumakuru": ["Tumakuru", "Tiptur", "Kunigal", "Sira", "Madhugiri", "Pavagada", "Chiknayakanhalli", "Gubbi"],
  "Ramanagara": ["Ramanagara", "Channapatna", "Kanakapura", "Magadi", "Bidadi"],
  "Chikkaballapur": ["Chikkaballapur", "Chintamani", "Gauribidanur", "Sidlaghatta", "Bagepalli"],
  "Kolar": ["Kolar", "KGF", "Bangarapet", "Malur", "Mulbagal", "Srinivaspur"],
  "Belagavi": ["Belagavi", "Nippani", "Chikodi", "Gokak", "Bailhongal", "Athani", "Ramdurg", "Saundatti"],
  "Bagalkot": ["Bagalkot", "Jamkhandi", "Mudhol", "Badami", "Ilkal", "Hungund", "Rabkavi Banhatti"],
  "Vijayapura": ["Vijayapura", "Indi", "Sindgi", "Muddebihal", "Basavana Bagevadi", "Talikot"],
  "Bidar": ["Bidar", "Bhalki", "Basavakalyan", "Humnabad", "Aurad", "Chitgoppa"],
  "Kalaburagi": ["Kalaburagi", "Sedam", "Aland", "Afzalpur", "Chittapur", "Chincholi", "Shahabad"],
  "Yadgir": ["Yadgir", "Shahapur", "Shorapur", "Gurmatkal", "Hunsagi"],
  "Raichur": ["Raichur", "Sindhanur", "Manvi", "Lingasugur", "Devadurga", "Maski"],
  "Koppal": ["Koppal", "Gangavathi", "Kushtagi", "Yelburga", "Kanakagiri"],
  "Ballari": ["Ballari", "Siruguppa", "Sanduru", "Kampli"],
  "Vijayanagara": ["Hosapete", "Hagaribommanahalli", "Harapanahalli", "Kudligi", "Kottur"],
  "Gadag": ["Gadag-Betageri", "Ron", "Naragund", "Mundargi", "Lakshmeshwara"],
  "Dharwad": ["Hubballi", "Dharwad", "Kalghatgi", "Kundgol", "Navalgund", "Annigeri"],
  "Haveri": ["Haveri", "Ranebennur", "Byadgi", "Hangal", "Hirekerur", "Savanur", "Shiggaon"],
  "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur", "Hanur"],
};